const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Stock = require('../models/Stock');
const path = require('path');

// Try to load .env from backend directory if running from script
const envPath = path.resolve(__dirname, '../.env');
dotenv.config({ path: envPath });

// Fallback: if MONGO_URI is missing, try default config (e.g. running from root)
if (!process.env.MONGO_URI) {
    dotenv.config();
}

const rawData = `
'786','786 Investments Limited'
'786R','786 Investment (Right)'
'AABS','Al-Abbas Sugar Mills Limited'
'AAL','Agro Allianz Limited(DEF)'
'AASM','Al-Abid Silk Mills Limited(DEF)'
'AATM','Ali Asghar Textile Mills Limited'
'ABL','Allied Bank Limited'
'ABOT','Abbott Laboratories (Pakistan) Limited'
'ABSON','Abson Industries Limited(DEF)'
'ACIETF','Alfalah Consumer Index (ETF)'
'ACPL','Attock Cement Pakistan Limited'
'ADAMS','Adam Sugar Mills Limited(XD)'
'ADMM','Artistic Denim Mills Limited'
'AGHA','Agha Steel Ind.Ltd'
'AGIC','Askari General Insurance Company Limited'
'AGICR2','Askari General Insurance Co.Ltd.(Right)'
'AGIL','Agriauto Industries Limited'
'AGL','Agritech Limited'
'AGLNCPS','Agritech Non-Voting (Pref) Class A'
'AGP','AGP Limited'
'AGSML','Abdullah Shah Ghazi Sugar Mills Limited'
'AGTL','Al-Ghazi Tractors Limited'
'AHCL','Arif Habib Corporation Limited'
'AHL','Arif Habib Limited'
'AHTM','Ahmad Hassan Textile Mills Limited'
'AICL','Adamjee Insurance Company Limited'
'AIRLINK','Air Link Communication Limited'
'AKBL','Askari Bank Limited'
'AKDHL','AKD Hospitality Limited'
'AKDSL','AKD Securities Limited'
'AKGL','Al-Khair Gadoon Limited'
'ALAC','Askari Life Assurance Company Limited'
'ALIFE','Adamjee Life Assurance Company Limited'
'ALNRS','Al-Noor Sugar Mills Limited(XD)'
'ALTN','Altern Energy Limited'
'AMBL','Apna Microfinance Bank Limited'
'AMSL','Al-Mal Securities & Services Limited(DEF)'
'AMTEX','Amtex Limited(DEF)'
'ANL','Azgard Nine Limited'
'ANLNV','Azgard Nine Non-Voting Ordinary Shares'
'ANLPS','Azgard Nine 8.95%(Pref)'
'ANNT','Annoor Textile Mills Limited(DEF)'
'ANSM','Ansari Sugar Mills Limited'
'ANTM','AN Textile Mills Limited'
'APL','Attock Petroleum Limited'
'APOT','Apollo Textile Mills Limited(DEF)'
'ARCTM','Arctic Textile Mills Limited'
'ARPAK','Arpak International Investments Ltd.'
'ARPL','Archroma Pakistan Limited'
'ARUJ','Aruj Industries Limited(DEF)'
'ASC','Al Shaheer Corporation Limited(DEF)'
'ASHT','Ashfaq Textile Mills Limited'
'ASIC','Asia Insurance Company Limited'
'ASL','Aisha Steel Mills Limited'
'ASLCPS','Aisha Steel Convt (Pref) Right'
'ASLPS','Aisha Steel Convertible (Pref)'
'ASTL','Amreli Steels Limited'
'ASTM','Asim Textile Mills Limited(DEF)'
'ATBA','Atlas Battery Limited'
'ATIL','Atlas Insurance Limited'
'ATLH','Atlas Honda Limited'
'ATRL','Attock Refinery Limited'
'AVN','Avanceon Limited'
'AWTX','Allawasaya Tex. & Finishing Mills Ltd'
'AZMT','Azmat Textile Mills Limited(DEF)'
'BAFL','Bank Alfalah Limited'
'BAFS','Baba Farid Sugar Mills Limited(XD)'
'BAHL','Bank AL Habib Limited'
'BAPL','Bawany Air Products Limited'
'BATA','Bata Pakistan Limited'
'BBFL','Big Bird Foods Limited'
'BCL','Bolan Castings Limited'
'BECO','Beco Steel Limited'
'BELA','Bela Automotives Limited(DEF)'
'BERG','Berger Paints Pakistan Limited'
'BFAGRO','Barkat Frisian Agro Limited'
'BFBIO','BF Biosciences Limited'
'BFMOD','B.F. Modaraba'
'BGL','Baluchistan Glass Limited'
'BHAT','Bhanero Textile Mills Limited'
'BIFO','Biafo Industries Limited'
'BIIC','Business & Industrial Insurance Company(DEF)'
'BIPL','BankIslami Pakistan Limited'
'BLUEX','Blue-Ex Limited'
'BML','Bank Makramah Limited'
'BNL','Bunnys Limited'
'BNWM','Bannu Woollen Mills Limited'
'BOK','The Bank of Khyber'
'BOP','The Bank of Punjab'
'BPL','Burshane LPG (Pakistan) Limited'
'BRRG','B.R.R Guardian Limited'
'BTL','Blessed Textiles Limited'
'BUXL','Buxly Paints Limited'
'BWCL','Bestway Cement Limited'
'BWHL','Baluchistan Wheels Limited'
'CASH','Calcorp Limited'
'CCM','Crescent Cotton Mills Limited'
'CENI','Century Insurance Company Limited'
'CEPB','Century Paper & Board Mills Limited'
'CFL','Crescent Fibres Limited'
'CHAS','Chashma Sugar Mills Limited'
'CHBL','Chenab Limited'
'CHCC','Cherat Cement Company Limited'
'CJPL','Crescent Jute Products Limited(DEF)'
'CLCPS','Chenab Limited (Pref)'
'CLOV','Clover Pakistan Limited'
'CLVL','Cordoba Logistics & Ventures Limited'
'CNERGY','Cnergyico PK  Limited'
'COLG','Colgate-Palmolive (Pakistan) Limited'
'CPHL','Citi Pharma Ltd.'
'CPPL','Cherat Packaging Limited'
'CRTM','The Crescent Textile Mills Limited'
'CSAP','Crescent Steel & Allied Products Limited'
'CSIL','Crescent Star Insurance Limited(R)'
'CTM','Colony Textile Mills Limited'
'CYAN','Cyan Limited'
'DAAG','Data Agro Limited'
'DADX','Dadex Eternit Limited'
'DBCI','Dadabhoy Cement Industries Limited(DEF)'
'DBSL','Dadabhoy Sack Limited(DEF)'
'DCL','Dewan Cement Limited'
'DCR','Dolmen City REIT'
'DCTL','Dadabhoy Construction Technology Limited(DEF)'
'DEL','Dawood Equities Limited'
'DFML','Dewan Farooque Motors Limited(DEF)'
'DFSM','Dewan Farooque Spinning Mills Limited(DEF)'
'DGKC','D.G. Khan Cement Company Limited'
'DHPL','DH Partners Limited'
'DIIL','Diamond Industries Limited'
'DINT','Din Textile Mills Limited'
'DKTM','Dewan Khalid Textile Mills Limited(DEF)'
'DLL','Dawood Lawrencepur Limited'
'DMC','D.M. Corporation Limited.'
'DMTM','Dewan Mushtaq Textile Mills Limited(DEF)'
'DNCC','Dandot Cement Company Limited'
'DOL','Descon Oxychem Limited'
'DSFL','Dewan Salman Fibre Limited(DEF)'
'DSIL','D.S. Industries Limited'
'DSL','Dost Steels Limited(DEF)'
'DWAE','Dewan Automotive Engineering Limited(DEF)'
'DWSM','Dewan Sugar Mills Limited(DEF)'
'DWTM','Dewan Textile Mills Limited(DEF)'
'DYNO','Dynea Pakistan Limited'
'ECOP','Ecopack Limited'
'EFERT','Engro Fertilizers Limited'
'EFUG','EFU General Insurance Limited'
'EFUL','EFU Life Assurance Limited'
'ELCM','Elahi Cotton Mills Limited'
'ELSM','Ellcot Spinning Mills Limited'
'EMCO','Emco Industries Limited'
'ENGL','English Leasing Limited(DEF)'
'ENGROH','Engro Holdings Limited'
'EPCL','Engro Polymer & Chemicals Limited'
'EPCLPS','Engro Poly(Pref)'
'EPQL','Engro Powergen Qadirpur Limited'
'ESBL','Escorts Investment Bank Limited'
'EWIC','East West Insurance Company Limited'
'EXIDE','Exide Pakistan Limited'
'FABL','Faysal Bank Limited'
'FAEL','Fatima Enterprises Limited(DEF)'
'FANM','First Al-Noor Modaraba'
'FASM','Faisal Spinning Mills Limited'
'FATIMA','Fatima Fertilizer Company Limited'
'FCCL','Fauji Cement Company Limited'
'FCEL','First Capital Equities Limited(DEF)'
'FCEPL','Frieslandcampina Engro Pakistan Limited'
'FCIBL','First Credit and Investment Bank Limited'
'FCL','Fast Cables Limited'
'FCONM','First Constellation Modaraba'
'FCSC','First Capital Securities Corporation'
'FDPL','First Dawood Properties Limited'
'FECM','First Elite Capital Modaraba'
'FECTC','Fecto Cement Limited'
'FEM','First Equity Modaraba'
'FEROZ','Ferozsons Laboratories Limited'
'FFC','Fauji Fertilizer Company Limited'
'FFL','Fauji Foods Limited'
'FFLM','First Fidelity Leasing Modaraba'
'FHAM','First Habib Modaraba'
'FIBLM','First IBL Modaraba'
'FIL','Fateh Industries Limited(DEF)'
'FIM','First Investec Modaraba(DEF)'
'FIMM','First Imrooz Modaraba'
'FLYNG','Flying Cement Company Limited'
'FML','Feroze1888 Mills Limited'
'FNBM','First National Bank Modaraba(DEF)'
'FNEL','First National Equities Limited'
'FPJM','First Punjab Modaraba'
'FPRM','First Paramount Modaraba'
'FRCL','Frontier Ceramics Limited'
'FRSM','Faran Sugar Mills Limited'
'FSWL','Fateh Sports Wear Limited(DEF)'
'FTHM','Fateh Textile Mills Limited(DEF)'
'FTMM','First Treet Manufacturing Modaraba'
'FTSM','First Tri-Star Modaraba'
'FZCM','Fazal Cloth Mills Limited'
'GADT','Gadoon Textile Mills Limited'
'GAL','Ghandhara Automobiles Limited'
'GAMON','Gammon Pakistan Limited(DEF)'
'GATI','Gatron (Industries) Limited'
'GATM','Gul Ahmed Textile Mills Limited'
'GCIL','Ghani Chemical Industries Limited'
'GCWL','Ghani Chemworld Limited'
'GEMBCEM','Burj Clean Energy Modaraba(GEM)'
'GEMMEL','Mughal Energy Limited(GEM)'
'GEMNETS','Nets International Communication Limited'
'GEMPACRA','The Pakistan Credit Rating Agency Ltd'
'GEMPAPL','Pak Agro Packaging Limited(GEM)'
'GEMSPNL','Supernet Limited(XB)'
'GFIL','Ghazi Fabrics International Limited'
'GGGL','Ghani Global Glass Limited'
'GGL','Ghani Global Holdings Limited'
'GHGL','Ghani Glass Limited'
'GHNI','Ghandhara Industries Limited'
'GIL','Good Luck Industries Ltd.'
'GLAXO','GlaxoSmithKline Pakistan Limited'
'GLOT','Globe Textile Mills Limited(DEF)'
'GLPL','Gillette Pakistan Limited'
'GOC','GOC (Pak) Limited.'
'GRR','Globe Residency REIT'
'GRYL','Grays Leasing Limited'
'GSPM','Gulshan Spinning Mills Limited(DEF)'
'GTYR','Ghandhara Tyre & Rubber Company Limited'
'GUSM','Gulistan Spinning Mills Limited(DEF)'
'GUTM','Gulistan Textile Mills Limited(DEF)'
'GVGL','Ghani Value Glass Limited'
'GWLC','Gharibwal Cement Limited'
'HABSM','Habib Sugar Mills Limited(XD)'
'HADC','Haydari Construction Company Limited(DEF)'
'HAEL','Hala Enterprises Limited'
'HAFL','Hafiz Limited'
'HAJT','Hajra Textile Mills Limited(DEF)'
'HALEON','Haleon Pakistan Limited'
'HASCOL','Hascol Petroleum Limited(DEF)'
'HATM','Hamid Textile Mills Limited(DEF)'
'HBL','Habib Bank Limited'
'HBLTETF','HBL Total Treasury (ETF)'
'HCAR','Honda Atlas Cars (Pakistan) Limited'
'HGFA','HBL Growth Fund'
'HICL','Habib Insurance Company Limited'
'HIFA','HBL Investment Fund'
'HINO','Hinopak Motors Limited'
'HINOON','Highnoon Laboratories Limited'
'HIRAT','Hira Textile Mills Limited(DEF)'
'HKKT','Hakkim Textile Mills Limited(DEF)'
'HMB','Habib Metropolitan Bank Limited'
'HMIM','Haji Mohammad Ismail Mills Limited(DEF)'
'HPL','Hoechst Pakistan Limited'
'HRPL','Habib Rice Product Limited.'
'HSPI','Huffaz Seamless Pipe Industries Limited(DEF)'
'HTL','Hi-Tech Lubricants Limited'
'HUBC','The Hub Power Company Limited'
'HUMNL','Hum Network Limited'
'HUSI','Husein Industries Limited'
'HWQS','Haseeb Waqas Sugar Mills Limited(DEF)'
'IBFL','Ibrahim Fibres Limited'
'IBLHL','IBL HealthCare Limited'
'ICCI','ICC Industries Limited'
'ICIBL','Invest Capital Investment Bank Limited'
'ICL','Ittehad Chemicals Limted'
'IDRT','Idrees Textile Mills Limited'
'IDSM','Ideal Spinning Mills Limited'
'IDYM','Indus Dyeing & Manufacturing Co. Limited'
'IGIHL','IGI Holdings Limited'
'IGIL','IGI Life Insurance Limited'
'ILP','Interloop Limited'
'IMAGE','Image Pakistan Limited'
'IML','Imperial  Limited(DEF)'
'IMS','Intermarket Securities Limited'
'INDU','Indus Motor Company Limited'
'INIL','International Industries Limited'
'INKL','International Knitwear Limited'
'INMF','Investec Mutual Fund Limited(DEF)'
'IPAK','International Packaging Films Limited(XB)'
'IREIT','Image Reit'
'ISIL','Ismail Industries Limited'
'ISL','International Steels Limited'
'ITANZ','Itanz Technologies Limited'
'ITTEFAQ','Ittefaq Iron Industries Limited'
'JATM','J.A. Textile Mills Limited(DEF)'
'JDMT','Janana De Malucho Textile Mills Limited'
'JDWS','JDW Sugar Mills Limited(XD)'
'JGICL','Jubilee General Insurance Limited'
'JKSM','J.K. Spinning Mills Limited'
'JLICL','Jubilee Life Insurance Company Limited'
'JSBL','JS Bank Limited'
'JSCL','Jahangir Siddiqui & Co. Ltd.'
'JSCLPSA','Jahangir Sidd(Pref)'
'JSGBETF','JS Global Banking Sector(ETF)'
'JSGCL','JS Global Capital Limited'
'JSIL','JS Investments Limited'
'JSMFETF','JS Momentum Factor Exchange Traded Fund(XD)'
'JSML','Jauharabad Sugar Mills Limited'
'JUBS','Jubilee Spinning & Weaving Mills Ltd.(DEF)'
'JVDC','Javedan Corporation Limited'
'JVDCPS','Javedan Corporation (Pref)'
'KAKL','Kaiser Arts & Krafts Limited(DEF)'
'KAPCO','Kot Addu Power Company Limited'
'KCL','Karam Ceramics Limited'
'KEL','K-Electric Limited'
'KHTC','Khyber Tobacco Company Limited'
'KHYT','Khyber Textile Mills Limited'
'KML','Kohinoor Mills Limited'
'KOHC','Kohat Cement Company Limited'
'KOHE','Kohinoor Energy Limited'
'KOHP','Kohinoor Power Company Limited'
'KOHTM','Kohat Textile Mills Limited'
'KOIL','Kohinoor Industries Limited'
'KOSM','Kohinoor Spinning Mills Limited'
'KPUS','Khairpur Sugar Mills Limited'
'KSBP','KSB Pumps Company Limited'
'KSTM','Khalid Siraj Textile Mills Limited(DEF)'
'KTML','Kohinoor Textile Mills Limited'
'LCI','Lucky Core Industries Limited'
'LEUL','Leather Up Limited'
'LIVEN','Liven Pharma Limited'
'LOADS','Loads Limited'
'LOTCHEM','Lotte Chemical Pakistan Limited'
'LPGL','Leiner Pak Gelatine Limited'
'LPL','Lalpir Power Limited'
'LSECL','LSE Capital Limited.'
'LSEFSL','LSE Financial Services Limited.'
'LSEVL','LSE Ventures Limited'
'LSEVLR','LSE Ventures Limited(RIGHT)'
'LUCK','Lucky Cement Limited'
'MACFL','MACPAC Films Limited'
'MACTER','Macter International Limited'
'MARI','Mari Energies Limited'
'MCB','MCB Bank Limited'
'MCBIM','MCB Investment Management Limited.'
'MDTL','Media Times Limited'
'MEBL','Meezan Bank Limited'
'MEHT','Mehmood Textile Mills Limited'
'MERIT','Merit Packaging Limited'
'MFFL','Mitchells Fruit Farms Limited'
'MFL','Matco Foods Limited'
'MFTM','Mohammad Farooq Textile Mills Limited(DEF)'
'MIIETF','Mahaana Islamic Index ETF'
'MIRKS','Mirpurkhas Sugar Mills Limited'
'MLCF','Maple Leaf Cement Factory Limited'
'MOHE','Mohib Exports Limited(DEF)'
'MQTM','Maqbool Textile Mills Limited'
'MRNS','Mehran Sugar Mills Limited'
'MSCL','Metropolitan Steel Corporation Limited'
'MSOT','Masood Textile Mills Limited'
'MSOTPS','Masood Textile (Pref)'
'MTL','Millat Tractors Limited'
'MUBT','Mubarak Textile Mills Limited(DEF)'
'MUGHAL','Mughal Iron & Steel Industries Limited'
'MUGHALC','Mughal Iron & Steel Industries Ltd(C)'
'MUREB','Murree Brewery Company Limited'
'MWMP','Mandviwala Mauser Plastic Industries'
'MZNPETF','Meezan Pakistan ETF'
'NAFL','National Fibres Limited(DEF)'
'NAGC','Nagina Cotton Mills Limited'
'NATF','National Foods Limited'
'NATM','Nadeem Textile Mills Limited'
'NBP','National Bank of Pakistan(XD)'
'NBPGETF','NBP Pakistan  Growth ETF'
'NCL','Nishat Chunian Limited'
'NCML','Nazir Cotton Mills Limited(DEF)'
'NCPL','Nishat Chunian Power Limited'
'NESTLE','Nestle Pakistan Limited'
'NETSOL','NetSol Technologies Limited'
'NEXT','Next Capital Limited'
'NICL','Nimir Industrial Chemicals Limited'
'NINA','Nina Industries Limited(DEF)'
'NITGETF','NIT Pakistan Gateway ETF'
'NMFL','Nirala MSR Foods Limited(DEF)'
'NML','Nishat Mills Limited'
'NONS','Noon Sugar Mills Limited(XD)'
'NPL','Nishat Power Limited'
'NRL','National Refinery Limited'
'NRSL','Nimir Resins Limited'
'NSRM','The National Silk & Rayon Mills Limited'
'OBOY','Oilboy Energy Limited'
'OCTOPUS','Octopus Digital Limited'
'OGDC','Oil & Gas Development Company Limited'
'OLPL','OLP Financial Services Pakistan Limited'
'OLPM','OLP Modaraba'
'OML','Olympia Mills Limited'
'ORM','Orient Rental Mod'
'OTSU','Otsuka Pakistan Limited'
'PABC','Pakistan Aluminium Beverage Cans Limited'
'PACE','Pace (Pakistan) Limited'
'PAEL','Pak Elektron Limited'
'PAKD','Pak Datacom Limited'
'PAKL','Pak Leather Crafts Limited'
'PAKOXY','Pakistan Oxygen Limited'
'PAKQATAR','Pak Qatar Family Takaful Limited'
'PAKRI','Pakistan Reinsurance Company Limited'
'PAKT','Pakistan Tobacco Company Limited'
'PASL','Pervez Ahmed Consultancy Services Ltd.(DEF)'
'PASM','Paramount Spinning Mills Limited(DEF)'
'PCAL','Pakistan Cables Limited'
'PECO','Pakistan Engineering Company Limited(DEF)'
'PGLC','Pak-Gulf Leasing Company Limited'
'PHDL','Pakistan Hotels Developers Limited(DEF)'
'PIAHCLA','PIA Holding Company Limited'
'PIAHCLB','PIA Holding Company LimitedB'
'PIBTL','Pakistan International Bulk Terminal'
'PICL','Pakistan Industrial & Commercial Leasing(DEF)'
'PICT','Pakistan International Container'
'PIL','PICIC Insurance Limited(DEF)'
'PIM','Popular Islamic Modaraba'
'PINL','Premier Insurance Limited'
'PIOC','Pioneer Cement Limited'
'PKGI','The Pakistan General Insurance Co. Ltd.'
'PKGP','Pakgen Power Limited'
'PKGS','Packages Limited'
'PMRS','The Premier Sugar Mills'
'PNSC','Pakistan National Shipping Corporation'
'POL','Pakistan Oilfields Limited'
'POML','Punjab Oil Mills Limited'
'POWER','Power Cement Limited'
'POWERPS','Power Cement (Pref)'
'PPL','Pakistan Petroleum Limited'
'PPP','Pakistan Paper Products Limited'
'PPVC','Pakistan PVC Limited(DEF)'
'PREMA','At-Tahur Limited'
'PRET','Premium Textile Mills Limited'
'PRIB','Prudential Investment Bank Limited(DEF)'
'PRIC','Progressive Insurance Company Limited(DEF)'
'PRL','Pakistan Refinery Limited'
'PRWM','Prosperity Weaving Mills Limited'
'PSEL','Pakistan Services Limited'
'PSO','Pakistan State Oil Company Limited'
'PSX','Pakistan Stock Exchange Limited'
'PSYL','Pakistan Synthetics Limited'
'PTC','Pakistan Telecommunication Company Ltd'
'PTL','Panther Tyres Ltd.'
'PUDF','Prudential Stocks Fund Limited(DEF)'
'QTECH','Quantum Data Technologies Limited(DEF)'
'QUET','Quetta Textile Mills Limited(DEF)'
'QUICE','Quice Food Industries Limited'
'RCML','Reliance Cotton Spinning Mills Limited'
'REDCO','Redco Textiles Limited'
'REGAL','Regal Ceramics Limited(DEF)'
'REWM','Reliance Weaving Mills Limited'
'RICL','Reliance Insurance Company Limited'
'RMPL','Rafhan Maize Products Company Limited'
'RPL','Roshan Packages Limited'
'RUBY','Ruby Textile Mills Limited(DEF)'
'RUPL','Rupali Polyester Limited'
'SAIF','Saif Textile Mills Limited'
'SANE','Salman Noman Enterprises Limited(DEF)'
'SANSM','Sanghar Sugar Mills Limited'
'SAPT','Sapphire Textile Mills Limited'
'SARC','Sardar Chemical Industries Limited'
'SASML','Sindh Abadgars Sugar Mills Limited(XD)'
'SAZEW','Sazgar Engineering Works Limited'
'SBL','Samba Bank Limited'
'SCBPL','Standard Chartered Bank (Pak) Ltd'
'SCHT','Schon Textiles Limited(DEF)'
'SCL','Shield Corporation Limited'
'SDOT','Sadoon Textile Industries Limited(DEF)'
'SEARL','The Searle Company Limited'
'SEL','Sitara Energy Limited'
'SEPL','Security Papers Limited'
'SERT','Service Industries Textiles Limited'
'SFAT','Safa Textiles Limited(DEF)'
'SFL','Sapphire Fibres Limited'
'SGABL','SG.Allied Businesses Limited(DEF)'
'SGF','Service GlobalFootwear Limited'
'SGPL','S.G. Power Limited'
'SHCI','Shaffi Chemical Industries Limited(DEF)'
'SHCM','Shadman Cotton Mills Limited'
'SHDT','Shadab Textile Mills Limited'
'SHEZ','Shezan International Limited'
'SHFA','Shifa International Hospitals Limited'
'SHJS','Shahtaj Sugar Mills Limited(XD)'
'SHNI','Shaheen Insurance Company Limited'
'SHSML','Shahmurad Sugar Mills Limited(XD)'
'SIBL','Security Investment Bank Limited'
'SIEM','Siemens (Pakistan) Engineering'
'SINDM','Sindh Modaraba'
'SITC','Sitara Chemical Industries Limited'
'SKRS','Sakrand Sugar Mills Limited(DEF)'
'SLCL','Security Leasing Corporation Limited(DEF)'
'SLCPA','Security Leasing Corp.9.10%(Pref)'
'SLGL','Secure Logistics-Trax Group Limited'
'SLL','SME Leasing Limited(DEF)'
'SLYT','Sally Textile Mills Limited(DEF)'
'SMCPL','Safe Mix Concrete Limited'
'SML','Shakarganj Limited(DEF)'
'SNAI','Sana Industries Limited'
'SNBL','Soneri Bank Limited'
'SNGP','Sui Northern Gas Pipelines Limited'
'SPCL','Saudi Pak Consultancy Company Limited(DEF)'
'SPEL','SPEL Limited'
'SPL','Sitara Peroxide Limited(DEF)'
'SPWL','Saif Power Limited'
'SRVI','Service Industries Limited'
'SSGC','Sui Southern Gas Company Limited'
'SSIC','Silver Star Insurance Company Limited(DEF)'
'SSML','Saritow Spinning Mills Limited(DEF)'
'SSOM','S.S.Oil Mills Limited'
'STCL','Shabbir Tiles & Ceramics Limited'
'STJT','Shahtaj Textile Limited'
'STL','Supernet Technologies Limited'
'STML','Shams Textile Mills Limited'
'STPL','Siddiqsons Tin Plate Limited'
'STYLERS','Stylers International Limited'
'SUHJ','Suhail Jute Mills Limited(DEF)'
'SURAJ','Suraj Ghee Industries Limited(DEF)'
'SURC','Suraj Cotton Mills Limited'
'SUTM','Sunrays Textile Mills Limited'
'SWL','Standard Worldwide Limited(DEF)'
'SYM','Symmetry Group Limited'
'SYS','Systems Limited'
'SZTM','Shahzad Textile Mills Limited'
'TAJT','Taj Textile Mills Limited(DEF)'
'TATM','Tata Textile Mills Limited'
'TBL','Treet Battery Limited.'
'TCORP','Tariq Corporation Limited'
'TCORPCPS','Tariq Corporation Limited(Pref)'
'TELE','Telecard Limited'
'TGL','Tariq Glass Industries Limited'
'THALL','Thal Limited'
'THCCL','Thatta Cement Company Limited'
'TICL','The Thal Industries Corporation Limited(XD)'
'TOMCL','The Organic Meat Company Limited'
'TOWL','Towellers Limited'
'TPL','TPL Corp Limited'
'TPLI','TPL Insurance Limited'
'TPLL','TPL Life Insurance Limited'
'TPLP','TPL Properties Limited'
'TPLRF1','TPL REIT Fund I'
'TPLT','TPL Trakker Limited'
'TREET','Treet Corporation Limited'
'TRG','TRG Pakistan Limited'
'TRIBL','Trust Investment Bank Limited(DEF)'
'TRIPF','Tri-Pack Films Limited'
'TRSM','Trust Modaraba'
'TSBL','Trust Securities & Brokerage Limited'
'TSMF','Tri-Star Mutual Fund Limited'
'TSML','Tandlianwala Sugar Mills Limited'
'TSPL','Tri-Star Power Limited'
'UBDL','United Brands Limited'
'UBL','United Bank Limited'
'UBLPETF','UBLPakistan Enterprise ETF'
'UCAPM','Unicap Modaraba'
'UDLI','UDL International Limited'
'UDPL','United Distributors Pakistan Limited'
'UNIC','The United Insurance Company'
'UNITY','Unity Foods Limited'
'UPFL','Unilever Pakistan Foods Limited'
'USMT','Usman Textile Mills Limited(DEF)'
'UVIC','The Universal Insurance Company Limited'
'WAFI','Wafi Energy Pakistan Limited'
'WAHN','Wah Noble Chemicals Limited'
'WASL','Wasl Mobility Modaraba'
'WAVES','Waves Corporation Limited'
'WAVESAPP','Waves Home Appliances Limited'
'WTL','Worldcall Telecom Limited'
'YOUW','Yousaf Weaving Mills Limited'
'ZAHID','Zahidjee Textile Mills Limited'
'ZAL','Zarea Limited'
'ZELP','Zeal Pak Cement Factory Limited(DEF)'
'ZIL','ZIL Limited'
'ZTL','Zephyr Textiles Limited'
'ZUMA','Zuma Resources Limited(DEF)'
`;

async function seedStocks() {
    console.log('🌱 Adding PSX stocks to database...');
    try {
        if (!process.env.MONGO_URI) {
            throw new Error('MONGO_URI is not defined. Please check your .env file path.');
        }

        console.log('Connecting to MongoDB...');
        await mongoose.connect(process.env.MONGO_URI);

        // Parse raw data
        const lines = rawData.trim().split('\n');
        const stocks = lines.map(line => {
            // Remove quotes and split by comma, handling potential commas inside names
            // Format is 'SYMBOL','Name'
            const parts = line.split("','");
            if (parts.length < 2) return null;

            const symbol = parts[0].replace(/'/g, '').trim();
            const name = parts[1].replace(/'/g, '').trim();

            return {
                symbol,
                name,
                country: 'PK',
                exchange: 'PSX',
                isActive: true
            };
        }).filter(Boolean);

        console.log(`Found ${stocks.length} stocks to seed.`);

        // Upsert stocks
        let count = 0;
        for (const stock of stocks) {
            await Stock.findOneAndUpdate(
                { symbol: stock.symbol, country: stock.country },
                stock,
                { upsert: true, new: true }
            );
            count++;
            if (count % 50 === 0) process.stdout.write('.');
        }

        console.log(`\n✅ Successfully seeded ${count} stocks.`);
        process.exit(0);
    } catch (error) {
        console.error('\n❌ Error seeding stocks:', error);
        process.exit(1);
    }
}

seedStocks();
